# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lpr_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_container = QtWidgets.QLabel(self.centralwidget)
        self.frame_container.setGeometry(QtCore.QRect(10, 10, 521, 411))
        self.frame_container.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.frame_container.setObjectName("frame_container")
        self.videoTestButton = QtWidgets.QPushButton(self.centralwidget)
        self.videoTestButton.setGeometry(QtCore.QRect(650, 50, 81, 26))
        self.videoTestButton.setObjectName("videoTestButton")
        #self.videoTestButton.setVisible(False)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 10, 201, 91))
        self.groupBox.setObjectName("groupBox")
        self.imgTestButton = QtWidgets.QPushButton(self.groupBox)
        self.imgTestButton.setGeometry(QtCore.QRect(10, 40, 81, 26))
        self.imgTestButton.setObjectName("imgTestButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 110, 201, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plate_container = QtWidgets.QLabel(self.groupBox_2)
        self.plate_container.setGeometry(QtCore.QRect(10, 50, 181, 81))
        self.plate_container.setStyleSheet("background-color: rgb(215, 215, 215);")
        self.plate_container.setText("")
        self.plate_container.setObjectName("plate_container")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(540, 290, 201, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 181, 41))
        self.label_4.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 430, 201, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox.raise_()
        self.frame_container.raise_()
        self.videoTestButton.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.frame_container.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.frame_container.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.videoTestButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.videoTestButton.setText(_translate("MainWindow", "视频测试"))
        self.groupBox.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "测试"))
        self.imgTestButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.imgTestButton.setText(_translate("MainWindow", "图像测试"))
        self.groupBox_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "车牌"))
        self.plate_container.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.groupBox_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "识别结果"))
        self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">result</p></body></html>"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">视频源</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "车牌识别系统v1.0@scut.edu.cn"))

    def set_click_event(self, button, event):
        button.clicked.connect(event)
